### ISSUE TITLE
Add instructions how to install using Carthage

### ISSUE THREAD

**Issue by dasdom** [kylef/Mockingjay#11]
Thank you for this great project. I was thinking about doing this myself.

I don't want to use CocoaPods. Could you please add instructions how to install it manually of using Carthage.

I tried to build it using Carthage but it didn't work. The compiler doesn't find 'stub'.

**Comment by kylef** [comment]
Hi @dasdom, this underlying build issue should be resolved by 03aa252d7cc44dc8e683296964c1ad5394eb3ee9. Could you try again and see that solves your problem.

Personally I've never used Carthage and have no idea how you'd go about installing it though that. However, the premise of Carthage is that it can use a framework's Xcode project so in theory there shouldn't be any framework specific instructions.

**Comment by dasdom** [comment]
Still no luck. Unfortunately I don't have much experience with Carthage myself. So probably it's an error on my side.
Could you add instructions how to install it manually? I'll experiment and make a pull request when I found out. Thanks.

**Comment by kylef** [comment]
This really doesn't warrant Mockingjay specific installation instructions. Manual installation would be the same as any other framework.

---

#### Add the project as a submodule

```
$ git submodule add https://github.com/kylef/Mockingjay
$ git submodule update --init --recursive
```

#### Add the desired subproject:

![add-project](https://cloud.githubusercontent.com/assets/44164/6452889/ada1ac4a-c130-11e4-84a7-2e39fd813a1c.gif)

#### Link with the framework and add it as a dependency:

![link-with-framework](https://cloud.githubusercontent.com/assets/44164/6452892/b0ad20ea-c130-11e4-9ce9-90e597ab2d54.gif)

**Comment by rogernolan** [comment]
The instructions for adding Carthage support are very simple (or should be):

add ``` github "kylef/Mockingjay"  ``` to your  Cartfile and run
``` 
carthage update
```

then follow the Carthage instructions for adding the built framework to your project as a dependency.

Sadly this doesn't work. For some reason Carthage downloads and builds Mockingly but doesn't copy the built library to it's build folder.

**Comment by chivalrousbob** [comment]
try carthage update --platform iOS "Mockingjay"  instead of "kylef/Mockingjay"
